String configurePage;

void parseConfigurePage() {
  configurePage =  "<!DOCTYPE html>";
  configurePage += "<html>";
  configurePage += "<title>IOT Cloud</title>";
  configurePage += "<meta charset='UTF-8'>";
  configurePage += "<meta name='viewport' content='width=device-width, initial-scale=1'>";
  configurePage += "<link rel='stylesheet' href='https://www.w3schools.com/w3css/4/w3.css'>";
  configurePage += "<link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Lato'>";
  configurePage += "<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css'>";
  configurePage += "<style>";
  configurePage += "body,h1,h2,h3,h4,h5,h6 {font-family: 'Lato', sans-serif;}";
  configurePage += "body, html {";
  configurePage += "height: 100%;";
  configurePage += "color: #777;";
  configurePage += "line-height: 1.8;";
  configurePage += "}";
  configurePage += "";
  configurePage += "/* Create a Parallax Effect */";
  configurePage += ".bgimg{";
  configurePage += "background-attachment: fixed;";
  configurePage += "background-position: center;";
  configurePage += "background-repeat: no-repeat;";
  configurePage += "background-size: cover;";
  configurePage += "}";
  configurePage += "";
  configurePage += "/* Background Picture */";
  configurePage += ".bgimg {";
  configurePage += "background-image: url('/w3images/parallax1.jpg');";
  configurePage += "min-height: 100%;";
  configurePage += "}";
  configurePage += "";
  configurePage += ".w3-wide {letter-spacing: 10px;}";
  configurePage += ".w3-hover-opacity {cursor: pointer;}";
  configurePage += "";
  configurePage += "</style>";
  configurePage += "<body>";
  configurePage += "";
  configurePage += "<!-- Navbar (sit on top) -->";
  configurePage += "<div class='w3-top'>";
  configurePage += "<div class='w3-bar' id='myNavbar'>";
  configurePage += "<a class='w3-bar-item w3-button w3-hover-black w3-hide-medium w3-hide-large w3-right' href='javascript:void(0);' onclick='toggleFunction()' title='Toggle Navigation Menu'>";
  configurePage += "<i class='fa fa-bars'></i>";
  configurePage += "</a>";
  configurePage += "<a href='/Home' class='w3-bar-item w3-button'>HOME</a>";
  configurePage += "<a href='/Control' class='w3-bar-item w3-button w3-hide-small'><i class='fa fa-user'></i> CONTROL</a>";
  configurePage += "<a href='/Configure' class='w3-bar-item w3-button w3-hide-small'><i class='fa fa-th'></i> CONFIGURE</a>";
  configurePage += "<a href='/WifiReset' class='w3-bar-item w3-button w3-hide-small w3-right w3-hover-red'>WIFI RESET</a>";
  configurePage += "<a href='/FactoryReset' class='w3-bar-item w3-button w3-hide-small w3-right w3-hover-red'>FACTORY RESET</a>";
  configurePage += "<a href='https://github.com/ZGoode/IOT-Cloud' class='w3-bar-item w3-button w3-hide-small'><i class='fa fa-th'></i> ABOUT</a>";
  configurePage += "</a>";
  configurePage += "</div>";
  configurePage += "</div>";
  configurePage += "";
  configurePage += "<div class='bgimg w3-display-container w3-opacity-min' id='home'>";
  configurePage += "<div class='w3-display-middle' style='white-space:nowrap;'>";
  configurePage += "<form class='w3-container' action='/updateConfig' method='get'><h2>Cloud Config:</h2>";
  configurePage += "<p><label>User ID (for this interface)</label><input class='w3-input w3-border w3-margin-bottom' type='text' name='userid' value='%USERID%' maxlength='20'></p>";
  configurePage += "<p><label>Password </label><input class='w3-input w3-border w3-margin-bottom' type='password' name='stationpassword' value='%STATIONPASSWORD%'></p>";
  configurePage += "<p><label>OTA Password </label><input class='w3-input w3-border w3-margin-bottom' type='password' name='otapassword' value='%OTAPASSWORD%'></p>";
  configurePage += "<p><label>OpenWeatherMap API Key (get from <a href='https://openweathermap.org/' target='_BLANK'>here</a>)</label><input class='w3-input w3-border w3-margin-bottom' type='text' name='openWeatherMapApiKey' value='%WEATHERKEY%' maxlength='60'></p>";
  configurePage += "<p><label>City Code (get from <a href='https://openweathermap.org/find?q=' target='_BLANK'>here</a>)</label><input class='w3-input w3-border w3-margin-bottom' type='text' name='city1' value='%CITY1%' onkeypress='return isNumberKey(event)'></p>";
  configurePage += "<button class='w3-button w3-block w3-grey w3-section w3-padding' type='submit'>Save</button>";
  configurePage += "</form>";
  configurePage += "</div>";
  configurePage += "</div>";
  configurePage += "";
  configurePage += "<!-- Footer -->";
  configurePage += "<footer class='w3-center w3-black w3-padding-64 w3-opacity w3-hover-opacity-off'>";
  configurePage += "<div class='w3-xlarge w3-section'>";
  configurePage += "<a href='https://github.com/ZGoode/IOT-Cloud'><i class='fa fa-github w3-hover-opacity'></i></a>";
  configurePage += "<a href='https://twitter.com/FlamingBandaid'><i class='fa fa-twitter w3-hover-opacity'></i></a>";
  configurePage += "<a href='http://linkedin.com/in/zachary-goode-724441160'><i class='fa fa-linkedin w3-hover-opacity'></i></a>";
  configurePage += "</div>";
  configurePage += "</footer>";
  configurePage += "";
  configurePage += "</body>";
  configurePage += "</html>";
}
