String controlPage;

void parseControlPage() {
  controlPage =  "<!DOCTYPE html>";
  controlPage += "<html>";
  controlPage += "<title>IOT Cloud</title>";
  controlPage += "<meta charset='UTF-8'>";
  controlPage += "<meta name='viewport' content='width=device-width, initial-scale=1'>";
  controlPage += "<link rel='stylesheet' href='https://www.w3schools.com/w3css/4/w3.css'>";
  controlPage += "<link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Lato'>";
  controlPage += "<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css'>";
  controlPage += "<style>";
  controlPage += "body,h1,h2,h3,h4,h5,h6 {font-family: 'Lato', sans-serif;}";
  controlPage += "body, html {";
  controlPage += "height: 100%;";
  controlPage += "color: #777;";
  controlPage += "line-height: 1.8;";
  controlPage += "}";
  controlPage += "";
  controlPage += "/* Create a Parallax Effect */";
  controlPage += ".bgimg {";
  controlPage += "background-attachment: fixed;";
  controlPage += "background-position: center;";
  controlPage += "background-repeat: no-repeat;";
  controlPage += "background-size: cover;";
  controlPage += "}";
  controlPage += "";
  controlPage += "/* First image (Logo. Full height) */";
  controlPage += ".bgimg {";
  controlPage += "background-image: url('/w3images/parallax1.jpg');";
  controlPage += "min-height: 100%;";
  controlPage += "}";
  controlPage += "";
  controlPage += "/* Second image (Portfolio) */";
  controlPage += "";
  controlPage += ".w3-wide {letter-spacing: 10px;}";
  controlPage += ".w3-hover-opacity {cursor: pointer;}";
  controlPage += "";
  controlPage += "</style>";
  controlPage += "<body>";
  controlPage += "";
  controlPage += "<!-- Navbar (sit on top) -->";
  controlPage += "<div class='w3-top'>";
  controlPage += "<div class='w3-bar' id='myNavbar'>";
  controlPage += "<a class='w3-bar-item w3-button w3-hover-black w3-hide-medium w3-hide-large w3-right' href='javascript:void(0);' onclick='toggleFunction()' title='Toggle Navigation Menu'>";
  controlPage += "<i class='fa fa-bars'></i>";
  controlPage += "</a>";
  controlPage += "<a href='/Home' class='w3-bar-item w3-button'>HOME</a>";
  controlPage += "<a href='/Control' class='w3-bar-item w3-button w3-hide-small'><i class='fa fa-user'></i> CONTROL</a>";
  controlPage += "<a href='/Configure' class='w3-bar-item w3-button w3-hide-small'><i class='fa fa-th'></i> CONFIGURE</a>";
  controlPage += "<a href='/WifiReset' class='w3-bar-item w3-button w3-hide-small w3-right w3-hover-red'>WIFI RESET</a>";
  controlPage += "<a href='/FactoryReset' class='w3-bar-item w3-button w3-hide-small w3-right w3-hover-red'>FACTORY RESET</a>";
  controlPage += "<a href='https://github.com/ZGoode/IOT-Cloud' class='w3-bar-item w3-button w3-hide-small'><i class='fa fa-th'></i> ABOUT</a>";
  controlPage += "</a>";
  controlPage += "</div>";
  controlPage += "</div>";
  controlPage += "";
  controlPage += "<!-- First Parallax Image with Logo Text -->";
  controlPage += "<div class='bgimg w3-display-container w3-opacity-min' id='home'>";
  controlPage += "<div class='w3-display-middle' style='white-space:nowrap;'>";
  controlPage += "";
  controlPage += "<h2><center><b>Cloud Mode: %MODE%</b></center></h2>";
  controlPage += "";
  controlPage += "<p><a href='/Automatic' class='w3-bar-item w3-button w3-hide-small'><i class='fa fa-user'></i> AUTOMATIC</a>";
  controlPage += "<a href='/ClearClouds' class='w3-bar-item w3-button w3-hide-small'><i class='fa fa-sun-o'></i> CLEAR CLOUDS</a>";
  controlPage += "<a href='/SpringDay' class='w3-bar-item w3-button w3-hide-small'><i class='fa fa-spinner'></i> SPRING DAY</a></p>";
  controlPage += "<p><a href='/RainbowSky' class='w3-bar-item w3-button w3-hide-small'><i class='fa fa-star-o'></i> RAINBOW SKY</a>";
  controlPage += "<a href='/LightningStorm' class='w3-bar-item w3-button w3-hide-small'><i class='fa fa-bolt'></i> LIGHTNING STORM</a>";
  controlPage += "<a href='/Rain' class='w3-bar-item w3-button w3-hide-small'><i class='fa fa-tint'></i> RAIN</a></p>";
  controlPage += "<p><a href='/Snow' class='w3-bar-item w3-button w3-hide-small'><i class='fa fa-snowflake-o'></i> SNOW</a>";
  controlPage += "<a href='/RainbowCycles' class='w3-bar-item w3-button w3-hide-small'><i class='fa fa-smile-o'></i> RAINBOW CYCLES</a>";
  controlPage += "<a href='/Cloudy' class='w3-bar-item w3-button w3-hide-small'><i class='fa fa-cloud'></i> CLOUDY</a></p>";
  controlPage += "";
  controlPage += "</div>";
  controlPage += "</div>";
  controlPage += "";
  controlPage += "<!-- Footer -->";
  controlPage += "<footer class='w3-center w3-black w3-padding-64 w3-opacity w3-hover-opacity-off'>";
  controlPage += "<div class='w3-xlarge w3-section'>";
  controlPage += "<a href='https://github.com/ZGoode/IOT-Cloud'><i class='fa fa-github w3-hover-opacity'></i></a>";
  controlPage += "<a href='https://twitter.com/FlamingBandaid'><i class='fa fa-twitter w3-hover-opacity'></i></a>";
  controlPage += "<a href='http://linkedin.com/in/zachary-goode-724441160'><i class='fa fa-linkedin w3-hover-opacity'></i></a>";
  controlPage += "</div>";
  controlPage += "</footer>";
  controlPage += "";
  controlPage += "</body>";
  controlPage += "</html>";
  controlPage += "";
  controlPage += "}";
}
